version: '2.3'

services:
    app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./logs:/logs
            - ./uploaded_files:/uploaded_files
        restart: unless-stopped
    tg-bot:
        image: lqrhy3/yop-cloud-telegram-bot:latest
        env_file:
            - .tg-bot.env

volumes:
    uploaded_files:
    postgres_data: