networks:
  internal:
  edge:


volumes:
  db_data:
  logs:
  nginx:
  s3data:
  alembic:


x-app-common: &x-app-common
  restart: always
  depends_on:
    db:
      condition: service_healthy
      restart: true
    s3:
      condition: service_healthy
      restart: true
  volumes:
    - ./alembic:/code/alembic
  env_file:
    - .env
  environment:
    - DOMAIN=${DOMAIN}
    - ENVIRONMENT=${ENVIRONMENT}
    - PROJECT_NAME=${PROJECT_NAME?Variable not set}
    - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
    - SECRET_KEY=${SECRET_KEY?Variable not set}
    - POSTGRES_SERVER=db
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER?Variable not set}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
    - SENTRY_DSN=${SENTRY_DSN}
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8000/health-check" ]
    interval: 100s
    timeout: 5s
    retries: 5

services:
  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./db_data:/var/lib/postgresql/data/pgdata
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    networks: [ internal ]

  s3:
    image: quay.io/minio/minio
    volumes:
      - ./s3data:/data
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?Variable not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?Variable not set}
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [ internal ]

  writer:
    <<: *x-app-common
    image: 'writer:${TAG-latest}'
    build:
      context: writer
      dockerfile: Dockerfile
    networks: [ internal ]

  reader:
    <<: *x-app-common
    image: 'reader:${TAG-latest}'
    build:
      context: reader
      dockerfile: Dockerfile
    networks: [ internal ]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - writer
    networks: [ internal, edge ]

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks: [ internal, edge ]
