version: '2.3'

services:
    app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./:/app
        restart: unless-stopped
    db:
        image: postgres:14
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data: