version: '2.3'

services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
            - ${LOCAL_STORAGE_DATA_PATH}:/storage_data
            - ./logs:/logs

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d:ro
        depends_on:
            - app

#    tg-bot:
#        image: lqrhy3/yop-cloud-telegram-bot:latest
#        env_file:
#            - .tg-bot.env

volumes:
    logs:
